repos:

  - repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
      - id: black

  - repo: https://github.com/asottile/seed-isort-config
    rev: v1.9.2
    hooks:
      - id: seed-isort-config
        args:
          - --application-directories=src:.

  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v4.3.21
    hooks:
      - id: isort

  - repo: https://gitlab.com/pycqa/flake8.git
    rev: 3.7.8
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-bugbear==20.1.4

  - repo: https://github.com/asottile/pyupgrade
    rev: v2.1.0
    hooks:
    - id: pyupgrade
      args:
        - --py36-plus

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-byte-order-marker
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: debug-statements
      - id: end-of-file-fixer
      - id: trailing-whitespace
