package:
  name: structure2vec
  version: 0.1.0.dev0

source:
  path: .

build:
  noarch: python
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  host:
    - python >=3.6
    - setuptools >=30.3
  run:
    - python >=3.6
    - networkx >=2.4,<3
    - numpy >=1.18,<2
    - scipy >=1.4,<2
    - pytorch >=1.4,<2

test:
  imports:
    - structure2vec.discriminative_embedding
    - structure2vec.graphs
